/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CollectorRouteImport } from './routes/collector'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecyclerRouteImport } from './routes/recycler'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminCollectorsRouteImport } from './routes/admin.collectors'
import { Route as AdminLotsRouteImport } from './routes/admin.lots'
import { Route as AdminRecyclersRouteImport } from './routes/admin.recyclers'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminTraceabilityRouteImport } from './routes/admin.traceability'
import { Route as AdminTransactionsRouteImport } from './routes/admin.transactions'
import { Route as CollectorIndexRouteImport } from './routes/collector.index'
import { Route as CollectorEarningsRouteImport } from './routes/collector.earnings'
import { Route as CollectorLotsRouteImport } from './routes/collector.lots'
import { Route as CollectorNotificationsRouteImport } from './routes/collector.notifications'
import { Route as CollectorPickupRouteImport } from './routes/collector.pickup'
import { Route as CollectorPricesRouteImport } from './routes/collector.prices'
import { Route as CollectorProfileRouteImport } from './routes/collector.profile'
import { Route as CollectorRecyclersRouteImport } from './routes/collector.recyclers'
import { Route as CollectorSafetyRouteImport } from './routes/collector.safety'
import { Route as CollectorSellRouteImport } from './routes/collector.sell'
import { Route as CollectorTransactionsRouteImport } from './routes/collector.transactions'
import { Route as RecyclerIndexRouteImport } from './routes/recycler.index'
import { Route as RecyclerIncomingRouteImport } from './routes/recycler.incoming'
import { Route as RecyclerOffersRouteImport } from './routes/recycler.offers'
import { Route as RecyclerPickupsRouteImport } from './routes/recycler.pickups'
import { Route as RecyclerProfileRouteImport } from './routes/recycler.profile'
import { Route as RecyclerTransactionsRouteImport } from './routes/recycler.transactions'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectorRoute = CollectorRouteImport.update({
  id: '/collector',
  path: '/collector',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecyclerRoute = RecyclerRouteImport.update({
  id: '/recycler',
  path: '/recycler',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectorsRoute = AdminCollectorsRouteImport.update({
  id: '/collectors',
  path: '/collectors',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLotsRoute = AdminLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRecyclersRoute = AdminRecyclersRouteImport.update({
  id: '/recyclers',
  path: '/recyclers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTraceabilityRoute = AdminTraceabilityRouteImport.update({
  id: '/traceability',
  path: '/traceability',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTransactionsRoute = AdminTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => AdminRoute,
} as any)
const CollectorIndexRoute = CollectorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorEarningsRoute = CollectorEarningsRouteImport.update({
  id: '/earnings',
  path: '/earnings',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorLotsRoute = CollectorLotsRouteImport.update({
  id: '/lots',
  path: '/lots',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorNotificationsRoute = CollectorNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorPickupRoute = CollectorPickupRouteImport.update({
  id: '/pickup',
  path: '/pickup',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorPricesRoute = CollectorPricesRouteImport.update({
  id: '/prices',
  path: '/prices',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorProfileRoute = CollectorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorRecyclersRoute = CollectorRecyclersRouteImport.update({
  id: '/recyclers',
  path: '/recyclers',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorSafetyRoute = CollectorSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorSellRoute = CollectorSellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => CollectorRoute,
} as any)
const CollectorTransactionsRoute = CollectorTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => CollectorRoute,
} as any)
const RecyclerIndexRoute = RecyclerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RecyclerRoute,
} as any)
const RecyclerIncomingRoute = RecyclerIncomingRouteImport.update({
  id: '/incoming',
  path: '/incoming',
  getParentRoute: () => RecyclerRoute,
} as any)
const RecyclerOffersRoute = RecyclerOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => RecyclerRoute,
} as any)
const RecyclerPickupsRoute = RecyclerPickupsRouteImport.update({
  id: '/pickups',
  path: '/pickups',
  getParentRoute: () => RecyclerRoute,
} as any)
const RecyclerProfileRoute = RecyclerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => RecyclerRoute,
} as any)
const RecyclerTransactionsRoute = RecyclerTransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => RecyclerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/collector': typeof CollectorRouteWithChildren
  '/login': typeof LoginRoute
  '/recycler': typeof RecyclerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/lots': typeof AdminLotsRoute
  '/admin/recyclers': typeof AdminRecyclersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/traceability': typeof AdminTraceabilityRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/collector/earnings': typeof CollectorEarningsRoute
  '/collector/lots': typeof CollectorLotsRoute
  '/collector/notifications': typeof CollectorNotificationsRoute
  '/collector/pickup': typeof CollectorPickupRoute
  '/collector/prices': typeof CollectorPricesRoute
  '/collector/profile': typeof CollectorProfileRoute
  '/collector/recyclers': typeof CollectorRecyclersRoute
  '/collector/safety': typeof CollectorSafetyRoute
  '/collector/sell': typeof CollectorSellRoute
  '/collector/transactions': typeof CollectorTransactionsRoute
  '/recycler/incoming': typeof RecyclerIncomingRoute
  '/recycler/offers': typeof RecyclerOffersRoute
  '/recycler/pickups': typeof RecyclerPickupsRoute
  '/recycler/profile': typeof RecyclerProfileRoute
  '/recycler/transactions': typeof RecyclerTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/collector/': typeof CollectorIndexRoute
  '/recycler/': typeof RecyclerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/lots': typeof AdminLotsRoute
  '/admin/recyclers': typeof AdminRecyclersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/traceability': typeof AdminTraceabilityRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/collector/earnings': typeof CollectorEarningsRoute
  '/collector/lots': typeof CollectorLotsRoute
  '/collector/notifications': typeof CollectorNotificationsRoute
  '/collector/pickup': typeof CollectorPickupRoute
  '/collector/prices': typeof CollectorPricesRoute
  '/collector/profile': typeof CollectorProfileRoute
  '/collector/recyclers': typeof CollectorRecyclersRoute
  '/collector/safety': typeof CollectorSafetyRoute
  '/collector/sell': typeof CollectorSellRoute
  '/collector/transactions': typeof CollectorTransactionsRoute
  '/recycler/incoming': typeof RecyclerIncomingRoute
  '/recycler/offers': typeof RecyclerOffersRoute
  '/recycler/pickups': typeof RecyclerPickupsRoute
  '/recycler/profile': typeof RecyclerProfileRoute
  '/recycler/transactions': typeof RecyclerTransactionsRoute
  '/admin': typeof AdminIndexRoute
  '/collector': typeof CollectorIndexRoute
  '/recycler': typeof RecyclerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/collector': typeof CollectorRouteWithChildren
  '/login': typeof LoginRoute
  '/recycler': typeof RecyclerRouteWithChildren
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/collectors': typeof AdminCollectorsRoute
  '/admin/lots': typeof AdminLotsRoute
  '/admin/recyclers': typeof AdminRecyclersRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/traceability': typeof AdminTraceabilityRoute
  '/admin/transactions': typeof AdminTransactionsRoute
  '/collector/earnings': typeof CollectorEarningsRoute
  '/collector/lots': typeof CollectorLotsRoute
  '/collector/notifications': typeof CollectorNotificationsRoute
  '/collector/pickup': typeof CollectorPickupRoute
  '/collector/prices': typeof CollectorPricesRoute
  '/collector/profile': typeof CollectorProfileRoute
  '/collector/recyclers': typeof CollectorRecyclersRoute
  '/collector/safety': typeof CollectorSafetyRoute
  '/collector/sell': typeof CollectorSellRoute
  '/collector/transactions': typeof CollectorTransactionsRoute
  '/recycler/incoming': typeof RecyclerIncomingRoute
  '/recycler/offers': typeof RecyclerOffersRoute
  '/recycler/pickups': typeof RecyclerPickupsRoute
  '/recycler/profile': typeof RecyclerProfileRoute
  '/recycler/transactions': typeof RecyclerTransactionsRoute
  '/admin/': typeof AdminIndexRoute
  '/collector/': typeof CollectorIndexRoute
  '/recycler/': typeof RecyclerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/collector'
    | '/login'
    | '/recycler'
    | '/admin/analytics'
    | '/admin/collectors'
    | '/admin/lots'
    | '/admin/recyclers'
    | '/admin/reports'
    | '/admin/traceability'
    | '/admin/transactions'
    | '/collector/earnings'
    | '/collector/lots'
    | '/collector/notifications'
    | '/collector/pickup'
    | '/collector/prices'
    | '/collector/profile'
    | '/collector/recyclers'
    | '/collector/safety'
    | '/collector/sell'
    | '/collector/transactions'
    | '/recycler/incoming'
    | '/recycler/offers'
    | '/recycler/pickups'
    | '/recycler/profile'
    | '/recycler/transactions'
    | '/admin/'
    | '/collector/'
    | '/recycler/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/analytics'
    | '/admin/collectors'
    | '/admin/lots'
    | '/admin/recyclers'
    | '/admin/reports'
    | '/admin/traceability'
    | '/admin/transactions'
    | '/collector/earnings'
    | '/collector/lots'
    | '/collector/notifications'
    | '/collector/pickup'
    | '/collector/prices'
    | '/collector/profile'
    | '/collector/recyclers'
    | '/collector/safety'
    | '/collector/sell'
    | '/collector/transactions'
    | '/recycler/incoming'
    | '/recycler/offers'
    | '/recycler/pickups'
    | '/recycler/profile'
    | '/recycler/transactions'
    | '/admin'
    | '/collector'
    | '/recycler'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/collector'
    | '/login'
    | '/recycler'
    | '/admin/analytics'
    | '/admin/collectors'
    | '/admin/lots'
    | '/admin/recyclers'
    | '/admin/reports'
    | '/admin/traceability'
    | '/admin/transactions'
    | '/collector/earnings'
    | '/collector/lots'
    | '/collector/notifications'
    | '/collector/pickup'
    | '/collector/prices'
    | '/collector/profile'
    | '/collector/recyclers'
    | '/collector/safety'
    | '/collector/sell'
    | '/collector/transactions'
    | '/recycler/incoming'
    | '/recycler/offers'
    | '/recycler/pickups'
    | '/recycler/profile'
    | '/recycler/transactions'
    | '/admin/'
    | '/collector/'
    | '/recycler/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CollectorRoute: typeof CollectorRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecyclerRoute: typeof RecyclerRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collector': {
      id: '/collector'
      path: '/collector'
      fullPath: '/collector'
      preLoaderRoute: typeof CollectorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recycler': {
      id: '/recycler'
      path: '/recycler'
      fullPath: '/recycler'
      preLoaderRoute: typeof RecyclerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collectors': {
      id: '/admin/collectors'
      path: '/collectors'
      fullPath: '/admin/collectors'
      preLoaderRoute: typeof AdminCollectorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lots': {
      id: '/admin/lots'
      path: '/lots'
      fullPath: '/admin/lots'
      preLoaderRoute: typeof AdminLotsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/recyclers': {
      id: '/admin/recyclers'
      path: '/recyclers'
      fullPath: '/admin/recyclers'
      preLoaderRoute: typeof AdminRecyclersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/traceability': {
      id: '/admin/traceability'
      path: '/traceability'
      fullPath: '/admin/traceability'
      preLoaderRoute: typeof AdminTraceabilityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/transactions': {
      id: '/admin/transactions'
      path: '/transactions'
      fullPath: '/admin/transactions'
      preLoaderRoute: typeof AdminTransactionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/collector/': {
      id: '/collector/'
      path: '/'
      fullPath: '/collector/'
      preLoaderRoute: typeof CollectorIndexRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/earnings': {
      id: '/collector/earnings'
      path: '/earnings'
      fullPath: '/collector/earnings'
      preLoaderRoute: typeof CollectorEarningsRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/lots': {
      id: '/collector/lots'
      path: '/lots'
      fullPath: '/collector/lots'
      preLoaderRoute: typeof CollectorLotsRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/notifications': {
      id: '/collector/notifications'
      path: '/notifications'
      fullPath: '/collector/notifications'
      preLoaderRoute: typeof CollectorNotificationsRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/pickup': {
      id: '/collector/pickup'
      path: '/pickup'
      fullPath: '/collector/pickup'
      preLoaderRoute: typeof CollectorPickupRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/prices': {
      id: '/collector/prices'
      path: '/prices'
      fullPath: '/collector/prices'
      preLoaderRoute: typeof CollectorPricesRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/profile': {
      id: '/collector/profile'
      path: '/profile'
      fullPath: '/collector/profile'
      preLoaderRoute: typeof CollectorProfileRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/recyclers': {
      id: '/collector/recyclers'
      path: '/recyclers'
      fullPath: '/collector/recyclers'
      preLoaderRoute: typeof CollectorRecyclersRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/safety': {
      id: '/collector/safety'
      path: '/safety'
      fullPath: '/collector/safety'
      preLoaderRoute: typeof CollectorSafetyRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/sell': {
      id: '/collector/sell'
      path: '/sell'
      fullPath: '/collector/sell'
      preLoaderRoute: typeof CollectorSellRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/collector/transactions': {
      id: '/collector/transactions'
      path: '/transactions'
      fullPath: '/collector/transactions'
      preLoaderRoute: typeof CollectorTransactionsRouteImport
      parentRoute: typeof CollectorRoute
    }
    '/recycler/': {
      id: '/recycler/'
      path: '/'
      fullPath: '/recycler/'
      preLoaderRoute: typeof RecyclerIndexRouteImport
      parentRoute: typeof RecyclerRoute
    }
    '/recycler/incoming': {
      id: '/recycler/incoming'
      path: '/incoming'
      fullPath: '/recycler/incoming'
      preLoaderRoute: typeof RecyclerIncomingRouteImport
      parentRoute: typeof RecyclerRoute
    }
    '/recycler/offers': {
      id: '/recycler/offers'
      path: '/offers'
      fullPath: '/recycler/offers'
      preLoaderRoute: typeof RecyclerOffersRouteImport
      parentRoute: typeof RecyclerRoute
    }
    '/recycler/pickups': {
      id: '/recycler/pickups'
      path: '/pickups'
      fullPath: '/recycler/pickups'
      preLoaderRoute: typeof RecyclerPickupsRouteImport
      parentRoute: typeof RecyclerRoute
    }
    '/recycler/profile': {
      id: '/recycler/profile'
      path: '/profile'
      fullPath: '/recycler/profile'
      preLoaderRoute: typeof RecyclerProfileRouteImport
      parentRoute: typeof RecyclerRoute
    }
    '/recycler/transactions': {
      id: '/recycler/transactions'
      path: '/transactions'
      fullPath: '/recycler/transactions'
      preLoaderRoute: typeof RecyclerTransactionsRouteImport
      parentRoute: typeof RecyclerRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminCollectorsRoute: typeof AdminCollectorsRoute
  AdminLotsRoute: typeof AdminLotsRoute
  AdminRecyclersRoute: typeof AdminRecyclersRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminTraceabilityRoute: typeof AdminTraceabilityRoute
  AdminTransactionsRoute: typeof AdminTransactionsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminCollectorsRoute: AdminCollectorsRoute,
  AdminLotsRoute: AdminLotsRoute,
  AdminRecyclersRoute: AdminRecyclersRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminTraceabilityRoute: AdminTraceabilityRoute,
  AdminTransactionsRoute: AdminTransactionsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CollectorRouteChildren {
  CollectorEarningsRoute: typeof CollectorEarningsRoute
  CollectorLotsRoute: typeof CollectorLotsRoute
  CollectorNotificationsRoute: typeof CollectorNotificationsRoute
  CollectorPickupRoute: typeof CollectorPickupRoute
  CollectorPricesRoute: typeof CollectorPricesRoute
  CollectorProfileRoute: typeof CollectorProfileRoute
  CollectorRecyclersRoute: typeof CollectorRecyclersRoute
  CollectorSafetyRoute: typeof CollectorSafetyRoute
  CollectorSellRoute: typeof CollectorSellRoute
  CollectorTransactionsRoute: typeof CollectorTransactionsRoute
  CollectorIndexRoute: typeof CollectorIndexRoute
}

const CollectorRouteChildren: CollectorRouteChildren = {
  CollectorEarningsRoute: CollectorEarningsRoute,
  CollectorLotsRoute: CollectorLotsRoute,
  CollectorNotificationsRoute: CollectorNotificationsRoute,
  CollectorPickupRoute: CollectorPickupRoute,
  CollectorPricesRoute: CollectorPricesRoute,
  CollectorProfileRoute: CollectorProfileRoute,
  CollectorRecyclersRoute: CollectorRecyclersRoute,
  CollectorSafetyRoute: CollectorSafetyRoute,
  CollectorSellRoute: CollectorSellRoute,
  CollectorTransactionsRoute: CollectorTransactionsRoute,
  CollectorIndexRoute: CollectorIndexRoute,
}

const CollectorRouteWithChildren = CollectorRoute._addFileChildren(
  CollectorRouteChildren,
)

interface RecyclerRouteChildren {
  RecyclerIncomingRoute: typeof RecyclerIncomingRoute
  RecyclerOffersRoute: typeof RecyclerOffersRoute
  RecyclerPickupsRoute: typeof RecyclerPickupsRoute
  RecyclerProfileRoute: typeof RecyclerProfileRoute
  RecyclerTransactionsRoute: typeof RecyclerTransactionsRoute
  RecyclerIndexRoute: typeof RecyclerIndexRoute
}

const RecyclerRouteChildren: RecyclerRouteChildren = {
  RecyclerIncomingRoute: RecyclerIncomingRoute,
  RecyclerOffersRoute: RecyclerOffersRoute,
  RecyclerPickupsRoute: RecyclerPickupsRoute,
  RecyclerProfileRoute: RecyclerProfileRoute,
  RecyclerTransactionsRoute: RecyclerTransactionsRoute,
  RecyclerIndexRoute: RecyclerIndexRoute,
}

const RecyclerRouteWithChildren = RecyclerRoute._addFileChildren(
  RecyclerRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CollectorRoute: CollectorRouteWithChildren,
  LoginRoute: LoginRoute,
  RecyclerRoute: RecyclerRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
